import fs from "fs/promises";
import path from "path";
import { randomUUID } from "crypto";
import { ConvexHttpClient } from "convex/browser";
import { GoogleGenAI } from "@google/genai";
import { api } from "../convex/_generated/api.js";
import {
  GEMINI_TTS_MODEL,
  GEMINI_VOICES,
  buildTtsPrompt,
  extractInlineAudioPart,
  generateGeminiAudio,
  toWaveBuffer
} from "./geminiTtsAdmin.js";

const DIRECT_CONCURRENCY = 2;
const BATCH_CHUNK_SIZE = 20;
const JOBS_DIRECTORY_NAME = "tts-bulk";
const JOBS_FILE_NAME = "jobs.json";
const MAX_ERROR_ITEMS = 20;
const BATCH_FINAL_STATES = new Set([
  "JOB_STATE_SUCCEEDED",
  "JOB_STATE_FAILED",
  "JOB_STATE_CANCELLED",
  "JOB_STATE_EXPIRED"
]);

let convexClient = null;
let geminiClient = null;
let bulkContext = null;
let jobsLoaded = false;
let persistJobsChain = Promise.resolve();
const jobs = new Map();

const normalizeField = (value) => (typeof value === "string" ? value.trim() : "");

const slugify = (input) => {
  const slug = String(input || "")
    .trim()
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");

  return slug || "untitled";
};

const getConvexClient = () => {
  if (convexClient) {
    return convexClient;
  }

  const url = process.env.CONVEX_URL;
  if (!url) {
    throw new Error("CONVEX_URL is not configured on the server.");
  }

  convexClient = new ConvexHttpClient(url);
  return convexClient;
};

const getGeminiClient = () => {
  if (geminiClient) {
    return geminiClient;
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured on the server.");
  }

  geminiClient = new GoogleGenAI({ apiKey });
  return geminiClient;
};

const formatErrorMessage = (error, fallbackMessage) => {
  if (error instanceof Error) {
    const rawMessage = error.message?.trim();
    if (rawMessage) {
      try {
        const parsed = JSON.parse(rawMessage);
        if (parsed?.error?.message) {
          return parsed.error.message;
        }
      } catch {
        return rawMessage;
      }

      return rawMessage;
    }
  }

  return fallbackMessage;
};

const getJobsFilePath = () => path.join(bulkContext.jobsDirectory, JOBS_FILE_NAME);

const ensureBulkDirectories = async () => {
  await fs.mkdir(bulkContext.jobsDirectory, { recursive: true });
  await fs.mkdir(bulkContext.audioRootDirectory, { recursive: true });
};

const persistJobs = async () => {
  persistJobsChain = persistJobsChain.catch(() => {}).then(async () => {
    await ensureBulkDirectories();
    const jobList = Array.from(jobs.values());
    const tempPath = `${getJobsFilePath()}.${randomUUID()}.tmp`;
    await fs.writeFile(tempPath, JSON.stringify(jobList, null, 2));
    await fs.rename(tempPath, getJobsFilePath());
  });

  return persistJobsChain;
};

const loadJobs = async () => {
  if (jobsLoaded) {
    return;
  }

  await ensureBulkDirectories();

  try {
    const raw = await fs.readFile(getJobsFilePath(), "utf8");
    const parsed = JSON.parse(raw);
    for (const job of Array.isArray(parsed) ? parsed : []) {
      jobs.set(job.id, job);
    }
  } catch (error) {
    if (error?.code !== "ENOENT") {
      console.warn("Failed to load bulk TTS jobs:", error);
    }
  }

  jobsLoaded = true;
};

const makeAudioCredit = (profileName, voiceName) =>
  `Generated by Gemini TTS (${profileName}, ${voiceName})`;

const buildQuestionTranscript = (questionText, options) => {
  const question = normalizeField(questionText);
  const normalizedQuestion = question.endsWith("?") ? question : `${question}?`;
  const normalizedOptions = Array.isArray(options)
    ? options.map((option) => normalizeField(option))
    : [];

  if (normalizedOptions.length !== 4 || normalizedOptions.some((option) => !option)) {
    throw new Error("Question options must contain exactly 4 non-empty values.");
  }

  return `${normalizedQuestion} ... Is it A: ${normalizedOptions[0]}, B: ${normalizedOptions[1]}, C: ${normalizedOptions[2]}, or D: ${normalizedOptions[3]}?`;
};

const buildQuestionPrompt = (profile, transcript) =>
  buildTtsPrompt({
    audioProfile: profile.audioProfile,
    style: profile.style,
    pace: profile.pace,
    accent: profile.accent,
    scene: profile.scene,
    sampleContext: profile.sampleContext,
    transcript
  });

const getProfileOutputDirectory = (profileName) =>
  path.join(bulkContext.audioRootDirectory, slugify(profileName));

const getQuestionAudioUrl = (profileName, questionId) =>
  `/audio/questions/${slugify(profileName)}/${questionId}.wav`;

const getQuestionAudioPath = (profileName, questionId) =>
  path.join(getProfileOutputDirectory(profileName), `${questionId}.wav`);

const saveWaveForItem = async (item, waveBuffer) => {
  const outputDirectory = getProfileOutputDirectory(item.profileName);
  await fs.mkdir(outputDirectory, { recursive: true });
  await fs.writeFile(getQuestionAudioPath(item.profileName, item.questionId), waveBuffer);
};

const addJobError = (job, item, message) => {
  if (job.errors.length >= MAX_ERROR_ITEMS) {
    return;
  }

  job.errors.push({
    questionId: item?.questionId || null,
    question: item?.question || null,
    message
  });
};

const markJobUpdated = (job) => {
  job.updatedAt = new Date().toISOString();
};

const summarizeJob = (job) => ({
  id: job.id,
  mode: job.mode,
  status: job.status,
  createdAt: job.createdAt,
  updatedAt: job.updatedAt,
  totalCount: job.totalCount,
  processedCount: job.processedCount,
  successCount: job.successCount,
  failureCount: job.failureCount,
  profileName: job.profile.profileName,
  voiceName: job.profile.voiceName,
  scope: job.selection.scope,
  categorySlug: job.selection.categorySlug,
  difficulty: job.selection.difficulty,
  onlyMissingAudio: job.selection.onlyMissingAudio,
  limit: job.selection.limit,
  errors: job.errors,
  remoteBatches: job.remoteBatches?.map((batch) => ({
    name: batch.name,
    state: batch.state,
    imported: batch.imported
  })) || []
});

const updateBatchAggregateState = (job) => {
  const batches = job.remoteBatches || [];
  const finalBatchCount = batches.filter((batch) => BATCH_FINAL_STATES.has(batch.state)).length;
  const failedBatch = batches.find((batch) => batch.state && batch.state !== "JOB_STATE_SUCCEEDED");

  if (job.processedCount >= job.totalCount) {
    job.status = job.failureCount > 0 ? "completed_with_errors" : "completed";
  } else if (failedBatch && finalBatchCount === batches.length) {
    job.status = job.successCount > 0 ? "completed_with_errors" : "failed";
  } else {
    job.status = "running";
  }
};

const finalizeDirectJob = async (job) => {
  if (job.processedCount >= job.totalCount) {
    job.status = job.failureCount > 0 ? "completed_with_errors" : "completed";
  } else if (job.failureCount > 0 && job.successCount === 0) {
    job.status = "failed";
  } else {
    job.status = "running";
  }

  markJobUpdated(job);
  await persistJobs();
};

const updateQuestionAudio = async (item, job) => {
  await getConvexClient().mutation(api.questions.setAudioMedia, {
    questionId: item.questionId,
    url: item.audioUrl,
    credit: makeAudioCredit(job.profile.profileName, job.profile.voiceName)
  });
};

const completeItemSuccess = async (job, item, waveBuffer) => {
  await saveWaveForItem(item, waveBuffer);
  await updateQuestionAudio(item, job);

  item.status = "completed";
  item.error = null;
  job.processedCount += 1;
  job.successCount += 1;
  markJobUpdated(job);
  await persistJobs();
};

const completeItemFailure = async (job, item, message) => {
  item.status = "failed";
  item.error = message;
  job.processedCount += 1;
  job.failureCount += 1;
  addJobError(job, item, message);
  markJobUpdated(job);
  await persistJobs();
};

const generateDirectItem = async (job, item) => {
  try {
    item.status = "running";
    markJobUpdated(job);
    await persistJobs();

    const { audioBuffer, mimeType } = await generateGeminiAudio({
      apiKey: process.env.GEMINI_API_KEY,
      prompt: item.prompt,
      voiceName: job.profile.voiceName
    });
    const waveBuffer = toWaveBuffer(audioBuffer, mimeType);
    await completeItemSuccess(job, item, waveBuffer);
  } catch (error) {
    await completeItemFailure(
      job,
      item,
      error instanceof Error ? error.message : "Failed to generate audio."
    );
  }
};

const runDirectJob = async (jobId) => {
  const job = jobs.get(jobId);
  if (!job) {
    return;
  }

  const queue = job.items.filter((item) => item.status === "pending");

  const workers = Array.from({ length: Math.min(DIRECT_CONCURRENCY, queue.length) }, async () => {
    while (queue.length > 0) {
      const nextItem = queue.shift();
      if (!nextItem) {
        return;
      }

      await generateDirectItem(job, nextItem);
    }
  });

  await Promise.all(workers);
  await finalizeDirectJob(job);
};

const chunkItems = (items, chunkSize) => {
  const chunks = [];
  for (let index = 0; index < items.length; index += chunkSize) {
    chunks.push(items.slice(index, index + chunkSize));
  }
  return chunks;
};

const extractBatchInlineResponses = (batchJob) => {
  if (Array.isArray(batchJob?.dest?.inlinedResponses)) {
    return batchJob.dest.inlinedResponses;
  }

  return [];
};

const importBatchChunkResults = async (job, batchChunk, batchJob) => {
  const responses = extractBatchInlineResponses(batchJob);

  for (let index = 0; index < batchChunk.itemIds.length; index += 1) {
    const itemId = batchChunk.itemIds[index];
    const item = job.items.find((entry) => entry.id === itemId);
    if (!item || item.status === "completed" || item.status === "failed") {
      continue;
    }

    const inlineResponse = responses[index];
    if (!inlineResponse) {
      await completeItemFailure(job, item, "Batch job returned no response for this question.");
      continue;
    }

    if (inlineResponse.error) {
      const message =
        inlineResponse.error.message ||
        inlineResponse.error.code ||
        "Batch request failed for this question.";
      await completeItemFailure(job, item, String(message));
      continue;
    }

    try {
      const inlineData = extractInlineAudioPart(inlineResponse.response);
      if (!inlineData?.data) {
        throw new Error("Batch response did not contain audio data.");
      }

      const waveBuffer = toWaveBuffer(
        Buffer.from(inlineData.data, "base64"),
        inlineData.mimeType || "audio/L16;rate=24000"
      );
      await completeItemSuccess(job, item, waveBuffer);
    } catch (error) {
      await completeItemFailure(
        job,
        item,
        error instanceof Error ? error.message : "Failed to import batch audio."
      );
    }
  }

  batchChunk.imported = true;
  markJobUpdated(job);
  await persistJobs();
};

const refreshBatchJob = async (job) => {
  const ai = getGeminiClient();

  for (const batchChunk of job.remoteBatches) {
    if (batchChunk.imported && BATCH_FINAL_STATES.has(batchChunk.state)) {
      continue;
    }

    try {
      const remoteBatch = await ai.batches.get({ name: batchChunk.name });
      batchChunk.state = remoteBatch.state;
      batchChunk.lastCheckedAt = new Date().toISOString();

      if (remoteBatch.state === "JOB_STATE_SUCCEEDED" && !batchChunk.imported) {
        await importBatchChunkResults(job, batchChunk, remoteBatch);
      } else if (
        remoteBatch.state &&
        remoteBatch.state !== "JOB_STATE_SUCCEEDED" &&
        BATCH_FINAL_STATES.has(remoteBatch.state) &&
        !batchChunk.imported
      ) {
        for (const itemId of batchChunk.itemIds) {
          const item = job.items.find((entry) => entry.id === itemId);
          if (!item || item.status === "completed" || item.status === "failed") {
            continue;
          }

          await completeItemFailure(
            job,
            item,
            remoteBatch.error?.message || `Batch job ended with state ${remoteBatch.state}.`
          );
        }
        batchChunk.imported = true;
      }
    } catch (error) {
      batchChunk.state = "JOB_STATE_FAILED";
      addJobError(
        job,
        null,
        formatErrorMessage(error, "Failed to refresh Gemini batch status.")
      );
      markJobUpdated(job);
      await persistJobs();
    }
  }

  updateBatchAggregateState(job);
  markJobUpdated(job);
  await persistJobs();
};

const createQuestionItems = (questions, profile) =>
  questions.map((questionDoc) => {
    const transcript = buildQuestionTranscript(questionDoc.question, questionDoc.options);
    const prompt = buildQuestionPrompt(profile, transcript);
    const questionId = String(questionDoc._id);

    return {
      id: randomUUID(),
      questionId,
      question: questionDoc.question,
      difficulty: questionDoc.difficulty,
      transcript,
      prompt,
      audioUrl: getQuestionAudioUrl(profile.profileName, questionId),
      status: "pending",
      error: null,
      profileName: profile.profileName
    };
  });

const createJobRecord = ({ mode, selection, profile, items }) => ({
  id: randomUUID(),
  mode,
  status: "queued",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  totalCount: items.length,
  processedCount: 0,
  successCount: 0,
  failureCount: 0,
  errors: [],
  selection,
  profile,
  items,
  remoteBatches: []
});

const resolveSelection = async (selection) => {
  const convex = getConvexClient();
  const normalizedLimit = Number.isInteger(selection.limit) && selection.limit > 0 ? selection.limit : null;
  let category = null;

  if (selection.scope === "category") {
    if (!selection.categorySlug || !selection.difficulty) {
      throw new Error("Category and difficulty are required for category-scoped runs.");
    }

    category = await convex.query(api.categories.getCategoryBySlug, {
      slug: selection.categorySlug
    });

    if (!category) {
      throw new Error("Selected category was not found.");
    }
  }

  const rows = await convex.query(api.questions.listForAudioAdmin, {
    categoryId: category?._id,
    difficulty: selection.scope === "category" ? selection.difficulty : undefined,
    enabledOnly: true,
    onlyMissingAudio: selection.onlyMissingAudio,
    limit: 10000
  });

  return {
    category,
    questions: normalizedLimit ? rows.slice(0, normalizedLimit) : rows
  };
};

const buildProfileFromBody = (body) => {
  const profileName = normalizeField(body.profileName);
  const voiceName = normalizeField(body.voiceName);

  if (!profileName) {
    throw new Error("Profile name is required.");
  }

  if (!GEMINI_VOICES.some((voice) => voice.name === voiceName)) {
    throw new Error("Voice name is invalid.");
  }

  return {
    profileName,
    voiceName,
    audioProfile: normalizeField(body.audioProfile),
    style: normalizeField(body.style),
    pace: normalizeField(body.pace),
    accent: normalizeField(body.accent),
    scene: normalizeField(body.scene),
    sampleContext: normalizeField(body.sampleContext)
  };
};

const buildSelectionFromBody = (body) => {
  const scope = normalizeField(body.scope) || "all";
  const difficulty = normalizeField(body.difficulty);
  const limitValue = Number(body.limit);

  if (!["all", "category"].includes(scope)) {
    throw new Error("Selection scope is invalid.");
  }

  if (scope === "all" && difficulty) {
    throw new Error("Difficulty filtering is only supported with category scope.");
  }

  return {
    scope,
    categorySlug: scope === "category" ? normalizeField(body.categorySlug) : "",
    difficulty: scope === "category" ? difficulty : "",
    onlyMissingAudio: body.onlyMissingAudio !== false,
    limit: Number.isFinite(limitValue) && limitValue > 0 ? Math.floor(limitValue) : null
  };
};

const buildBatchRequests = (job, items) =>
  items.map((item) => ({
    contents: [
      {
        role: "user",
        parts: [{ text: item.prompt }]
      }
    ],
    metadata: {
      questionId: item.questionId,
      itemId: item.id
    },
    config: {
      responseModalities: ["AUDIO"],
      speechConfig: {
        voiceConfig: {
          prebuiltVoiceConfig: {
            voiceName: job.profile.voiceName
          }
        }
      }
    }
  }));

const startBatchJob = async (job) => {
  const ai = getGeminiClient();
  const itemChunks = chunkItems(job.items, BATCH_CHUNK_SIZE);

  for (const items of itemChunks) {
    const remoteBatch = await ai.batches.create({
      model: GEMINI_TTS_MODEL,
      src: buildBatchRequests(job, items)
    });

    job.remoteBatches.push({
      name: remoteBatch.name,
      state: remoteBatch.state || "JOB_STATE_PENDING",
      imported: false,
      itemIds: items.map((item) => item.id),
      createdAt: new Date().toISOString(),
      lastCheckedAt: null
    });

    markJobUpdated(job);
    await persistJobs();
  }

  job.status = "running";
  markJobUpdated(job);
  await persistJobs();
};

const getRecentJobSummaries = () =>
  Array.from(jobs.values())
    .sort((left, right) => String(right.createdAt).localeCompare(String(left.createdAt)))
    .slice(0, 8)
    .map(summarizeJob);

const buildOptionsPayload = async () => {
  const convex = getConvexClient();
  const categoryTree = await convex.query(api.categories.listTree, {
    enabledOnly: true
  });

  return {
    voices: GEMINI_VOICES,
    categories: categoryTree.map((entry) => ({
      id: String(entry.category._id),
      name: entry.category.name,
      slug: entry.category.slug
    })),
    jobs: getRecentJobSummaries()
  };
};

export const registerGeminiTtsBulkAdminRoutes = async (app, { publicDir, dataDir }) => {
  bulkContext = {
    publicDir,
    dataDir,
    audioRootDirectory: path.join(publicDir, "audio", "questions"),
    jobsDirectory: path.join(dataDir, JOBS_DIRECTORY_NAME)
  };

  await loadJobs();

  app.get("/api/admin/tts-bulk/options", async (_req, res) => {
    try {
      const payload = await buildOptionsPayload();
      return res.json({ ok: true, ...payload });
    } catch (error) {
      return res.status(500).json({
        ok: false,
        error: error instanceof Error ? error.message : "Failed to load bulk TTS options."
      });
    }
  });

  app.post("/api/admin/tts-bulk/preview", async (req, res) => {
    try {
      const selection = buildSelectionFromBody(req.body || {});
      const { category, questions } = await resolveSelection(selection);

      return res.json({
        ok: true,
        count: questions.length,
        category: category
          ? { name: category.name, slug: category.slug }
          : null,
        sample: questions.slice(0, 5).map((question) => ({
          id: String(question._id),
          question: question.question,
          difficulty: question.difficulty,
          hasAudio: question.media?.type === "audio" && Boolean(question.media?.url)
        }))
      });
    } catch (error) {
      return res.status(400).json({
        ok: false,
        error: error instanceof Error ? error.message : "Failed to preview questions."
      });
    }
  });

  app.post("/api/admin/tts-bulk/start", async (req, res) => {
    let job = null;

    try {
      const mode = normalizeField(req.body?.mode) || "direct";
      if (!["direct", "batch"].includes(mode)) {
        throw new Error("Mode must be direct or batch.");
      }

      const selection = buildSelectionFromBody(req.body || {});
      const profile = buildProfileFromBody(req.body || {});
      const { questions } = await resolveSelection(selection);

      if (questions.length === 0) {
        throw new Error("No matching questions found for this run.");
      }

      const items = createQuestionItems(questions, profile);
      job = createJobRecord({ mode, selection, profile, items });
      jobs.set(job.id, job);
      await persistJobs();

      if (mode === "direct") {
        job.status = "running";
        markJobUpdated(job);
        await persistJobs();
        void runDirectJob(job.id);
      } else {
        await startBatchJob(job);
      }

      return res.json({
        ok: true,
        job: summarizeJob(job)
      });
    } catch (error) {
      if (job) {
        if ((job.remoteBatches || []).length === 0 && job.processedCount === 0) {
          jobs.delete(job.id);
        } else {
          job.status = "failed";
          addJobError(job, null, formatErrorMessage(error, "Failed to start bulk TTS run."));
          markJobUpdated(job);
        }
        await persistJobs();
      }

      return res.status(400).json({
        ok: false,
        error: formatErrorMessage(error, "Failed to start bulk TTS run.")
      });
    }
  });

  app.get("/api/admin/tts-bulk/jobs", async (_req, res) => {
    await loadJobs();
    return res.json({
      ok: true,
      jobs: getRecentJobSummaries()
    });
  });

  app.get("/api/admin/tts-bulk/jobs/:jobId", async (req, res) => {
    await loadJobs();
    const job = jobs.get(req.params.jobId);

    if (!job) {
      return res.status(404).json({ ok: false, error: "Job not found." });
    }

    try {
      if (job.mode === "batch" && ["queued", "running"].includes(job.status)) {
        await refreshBatchJob(job);
      }

      return res.json({
        ok: true,
        job: {
          ...summarizeJob(job),
          items: job.items.slice(0, 15).map((item) => ({
            questionId: item.questionId,
            question: item.question,
            difficulty: item.difficulty,
            status: item.status,
            audioUrl: item.audioUrl,
            error: item.error
          }))
        }
      });
    } catch (error) {
      return res.status(500).json({
        ok: false,
        error: error instanceof Error ? error.message : "Failed to load job status."
      });
    }
  });
};
